### ISSUE TITLE
Is it possible to build an app with some native jni code?

### ISSUE THREAD

**Issue by gekailin** [clojure-android/lein-droid#120]

**Comment by alexander-yakushev** [comment]
Yes, it is possible. I once used OpenCV in a CoA project. Fill in [:native-libraries-path](https://github.com/clojure-android/lein-droid/wiki/project.clj-options#native-libraries-paths), all the rest is quite straightforward.

**Comment by gekailin** [comment]
Thanks, but I still could not get it work. I run `ndk-build` first in my project directory, and it compiles my jni code into several `.so` files in the `libs/<arch>/` subdirectories. I added `:native-libraries-paths ["libs"]` into the `:android` section of my `project.clj`, and then run `lein droid doall`. But it makes no difference.

**Comment by alexander-yakushev** [comment]
When you build the project with `DEBUG=1`, does it say `Adding native libraries: <list>`?

**Comment by gekailin** [comment]
Thanks~ I didn't know the `DEBUG=1` thing before~

**Comment by alexander-yakushev** [comment]
So, did you manage to build your project?

**Comment by gekailin** [comment]
Yeah, it was my mistake. Thank you very much!

**Comment by alexander-yakushev** [comment]
You are welcome!
