### ISSUE TITLE
Lein-droid or neko

### ISSUE THREAD

**Issue by GildedHonour** [clojure-android/lein-droid#125]
That's not an issue but a question I can't find an answer for. Which one, lein-droid or neko, should I use to create a simple Hello World app in Android Studio in Clojure?

**Comment by alexander-yakushev** [comment]
Lein-droid is a build tool — it works on your computer and performs all the necessary steps to build your application from sources to an APK file.

Neko is a library. You use it from your Android application to implement functionality that would be too inconvenient to do with Java interop.

You create a new project with lein-droid as described in the [tutorial](https://github.com/clojure-android/lein-droid/wiki/Tutorial). This new project will already include Neko dependency.

Unfortunately, there is no special integration between Clojure-Android projects and Android Studio, but you can use any editor/IDE that support nREPL to work with CoA.

**Comment by GildedHonour** [comment]
Thanks.
