### ISSUE TITLE
nrepl dependency causing an error

### ISSUE THREAD

**Issue by cwhitey** [clojure-android/lein-droid#126]
Hi,

When using this dependency which is laid down by the droid template ```[org.clojure-android/tools.nrepl "0.2.10"]```, I would get the following error:

```
Could not transfer artifact org.clojure-android:tools.nrepl:pom:0.2.10 from/to clojars (https://clojars.org/repo/): Connect to clojars.org:443 [clojars.org/38.0.60.2] failed: Connection timed out
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Using this other dependency resolved the problem: ```[org.clojure-android/tools.nrepl "0.2.6-lollipop"]```

Let me know if you need some more info. I'm unsure of what could be causing this problem. I could always be doing something dumb :)

Regards,
Callum

**Comment by alexander-yakushev** [comment]
Oops! Good catch, it should be `[org.clojure/tools.nrepl "0.2.10"]`, because since `[org.clojure-android "1.7.0-alpha6"]` we don't need a separate nREPL fork anymore.

**Comment by GildedHonour** [comment]
By the way, the size of the apk of Hello World is 9 MB in Clojure, whereas in Kotlin it's 4Mb, in Java 3Mb for debug configuration. Are you aware of it? Is there any way to make it shrink it?

**Comment by alexander-yakushev** [comment]
http://clojure-android.info/skummet/
