### ISSUE TITLE
Two errors on lein droid repl

### ISSUE THREAD

**Issue by Malabarba** [clojure-android/lein-droid#128]
1. run `lein droid new someapp com.someapp`
2. set `:target-version "21"` in `project.clj`
3. run `lein droid doall`
4. run `lein droid repl`

I get the following output:

    REPL-y 0.3.5, nREPL 
    Clojure 1.7.0-alpha6
    Dalvik 0.9
    FileNotFoundException Could not locate clojure/java/javadoc__init.class or clojure/java/javadoc.clj on classpath.  clojure.lang.RT.load (RT.java:468)
    #<Namespace user>
    Error loading namespace; falling back to user
    nil
    user=>

I haven't actually run into any issues because of this (AFAICT), but I figured it's worth reporting.

**Comment by alexander-yakushev** [comment]
Gonna have a look, thank you for reporting.

**Comment by jitendranair** [comment]
1) The `lein droid repl` output does not display the `nrepl` version as seen in @Malabarba's  comment above, but for a non-droid project it does show : 
```
REPL-y 0.3.5, nREPL 0.2.10
Clojure 1.7.0
OpenJDK 64-Bit Server VM 1.7.0_79-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e
user=> 
```
2) May be this is the reason, in emacs doing a cider-connect on android project shows the error below :
```
; CIDER 0.9.1 (Java 0, Clojure 1.7.0-beta3-r2, nREPL nil)
WARNING: Can't determine nREPL's version. Please, update nREPL to 0.2.7.  
```

**Comment by alexander-yakushev** [comment]
Fixed the nREPL issue by pretending that nREPL version is always 0.2.10 :P. Proper fix for this would be even more ugly.

Also rewrote `lein droid repl` in d16ebd95c9c1051ae1993e85cddd0bd144eb5cbe so that REPLy won't complatin anymore.

**Comment by dferens** [comment]
@alexander-yakushev , this errors can be fixed easily by replacing
```clojure
{:dependencies [[org.clojure/tools.nrepl "0.2.10"]]}
```
with 
```clojure
{:dependencies [[org.clojure/tools.nrepl "0.2.10" :use-resources true]]
```
Isn't ugly at all.

**Comment by alexander-yakushev** [comment]
@dferens You are right, but it also embeds all tools.nrepl sources into the APK. That's not perfect. For the same reason I changed the version parsing in clojure.core to a hardcoded value, so that we can stop using `:use-resources true` for Clojure. Besides, it saves a solid 100 ms during load time which is also quite important.
