### ISSUE TITLE
Release Proguard in alpha6

### ISSUE THREAD

**Issue by AdamClements** [clojure-android/lein-droid#129]
(some paths replaced with <...>)

```<...>/android-sdk-linux/tools/proguard/bin/proguard.sh @<...>LeinDroid0.4.0/build/mainDexClasses.rules -injars <...>/:L:e:i:n:D:r:o:i:d:0:.:4:.:0:/:t:a:r:g:e:t:/:m:i:n:i:n:i:f:i:e:d:-:c:l:a:s:s:e:s:.:j:a:r -libraryjars <...>shrinkedAndroid.jar -outjars <...>```

I get an error when proguarding, the proguard command has the -injars minifiedclasses.jar string split and joined with a ":" between each letter, somewhere it's got confused for a vector.

**Comment by alexander-yakushev** [comment]
This is proguard for multidexing, right? It expects :target-paths to be a
vector. Shouldn't it?

**Comment by AdamClements** [comment]
Looks like it, except I don't set target-paths anywhere so it should be the default

**Comment by alexander-yakushev** [comment]
OK, I'll take a look when I get to the keyboard.

**Comment by alexander-yakushev** [comment]
So we consider this fixed.
