### ISSUE TITLE
Missing com.android.support:multidex

### ISSUE THREAD

**Issue by laurentpetit** [clojure-android/lein-droid#130]
When executing lein droid doall from the command line, I get this problem:

(I run OS X Yosemite 10.10.4)

```
tmp % java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

tmp % lein version
Leiningen 2.5.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM

tmp % lein new droid myapp com.myapp :target-sdk 19 :min-sdk 15
Retrieving droid/lein-template/0.1.4/lein-template-0.1.4.pom from clojars
Retrieving droid/lein-template/0.1.4/lein-template-0.1.4.jar from clojars
[...]
Retrieving com/android/tools/common/24.2.3/common-24.2.3.jar from central
[...]
Retrieving net/lingala/zip4j/zip4j/1.3.2/zip4j-1.3.2.jar from central
[...]
Using lein-droid 0.4.0-alpha6
Using lein-droid 0.4.0-alpha6

Creating project myapp ...
tmp % cd myapp

# Here I change one line of project.clj :             :sdk-path "/Users/laurentpetit/android-sdk-macosx/"

myapp % lein-stable droid doall
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
Retrieving org/clojure-android/clojure/1.7.0/clojure-1.7.0.pom from clojars
Retrieving neko/neko/4.0.0-alpha2/neko-4.0.0-alpha2.pom from clojars
Retrieving org/clojure-android/clojure/1.7.0-beta3-r2/clojure-1.7.0-beta3-r2.pom from clojars
Retrieving org/clojure-android/clojure/1.7.0/clojure-1.7.0.jar from clojars
Retrieving neko/neko/4.0.0-alpha2/neko-4.0.0-alpha2.jar from clojars
Could not find artifact com.android.support:multidex:aar:1.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.android.support:multidex:aar:1.0.0 in clojars (https://clojars.org/repo/)
Could not find artifact com.android.support:multidex:aar:1.0.0 in android-support (file:///Users/laurentpetit/android-sdk-macosx/extras/android/m2repository)
Could not find artifact com.android.support:multidex:aar:1.0.0 in android-play-services (file:///Users/laurentpetit/android-sdk-macosx/extras/google/m2repository)
Could not find artifact com.android.support:multidex:aar:1.0.0 in maven-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

I am not behind a proxy, and I have only modified project.clj to set the proper path to my android-sdk-macosx. I have tried the command twice in case the network had an intermittent problem

The same issue has been reproduced by @arichiardi on his Linux machine.

Reproduced while trying to start working on a lein-droid / Counterclockwise integration issue in https://github.com/laurentpetit/ccw/issues/840 , but as you see, got stopped before even being able to do things without involving CCW.

**Comment by laurentpetit** [comment]
OK, It's just that "Android Support Repository" was not checked by default and I didn't understand I had to do so. Closing the issue.

**Comment by alexander-yakushev** [comment]
Indeed. I think I've added to the docs a line about that repo, but perhaps
a better error message would help.

**Comment by arichiardi** [comment]
I think still an issue here, basically in my ```extras/m2repository``` I have ```multidex``` version ```1.0.1```, not ```1.0.0```...should it complain about it?

**Comment by alexander-yakushev** [comment]
Neko depends on 1.0.0, I don't know when Google updated it and why the old
version is not there. Try adding :exclusions
[com.android.support/multidex], and explicitly require the version you
have. Should work.

**Comment by arichiardi** [comment]
Yes, it solved. Thank you!

**Comment by alexander-yakushev** [comment]
Cool! But I still don't understand why they haven't kept the old version
for compatibility. I bet you've just downloaded SDK, haven't you?

**Comment by laurentpetit** [comment]
Yeah he probably so did, because for my tests I just installed everything
from scratch and got 1.0.0 version

2015-08-13 17:35 GMT+02:00 Alexander Yakushev <notifications@github.com>:

> Cool! But I still don't understand why they haven't kept the old version
> for compatibility. I bet you've just downloaded SDK, haven't you?
>
> On Thu, Aug 13, 2015, 18:32 Andrea Richiardi <notifications@github.com>
> wrote:
>
> > Yes, it solved. Thank you!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/clojure-android/lein-droid/issues/130#issuecomment-130731086
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-android/lein-droid/issues/130#issuecomment-130731769>
> .
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
It might have been a problem of my setup, I had to delete and reinstall from the SDK manager in order to have again both versions.
