### ISSUE TITLE
:exclude-aot-ns being ignored?

### ISSUE THREAD

**Issue by kenrestivo** [clojure-android/lein-droid#140]
I'm getting compile errors in the lein droid build target, for ns'es which are included in :exclude-aot-ns

This used to build with old (year ago) versions of lein-droid. Now it's not. Did something change and is there a new way to tell lein-droid not to aot compile certain namespaces?

**Comment by kenrestivo** [comment]
Pilot error. In previous versions of lein-droid, exclude namespaces were legal to specify as symbols. In this version. they must be strings. Changed to strings, problem so.ved

**Comment by alexander-yakushev** [comment]
Yes, they can be either strings or regular expressions now.

**Comment by alexander-yakushev** [comment]
Please report if you have any other difficulties with updating to latest lein-droid. We've changed quite a lot .
