### ISSUE TITLE
ENOENT using nrepl

### ISSUE THREAD

**Issue by kenrestivo** [clojure-android/lein-droid#142]
CompilerException java.lang.RuntimeException: java.io.IOException: open failed: ENOENT (No such file or directory), compiling:(NO_SOURCE_PATH:1:1) 

Can't seem to execute anything from nrepl.

Lein tree says:
```clojure
 [cheshire "5.5.0"]
 [cider/cider-nrepl "0.9.1"]
 [com.google.android/support-v4 "r7"]
 [neko "4.0.0-alpha5"]
 [org.clojure-android/clojure "1.7.0"]
 [org.clojure/tools.nrepl "0.2.10"]
 [utilza "0.1.73"]
```

I'll do some binary-search through to see if I can isolate it further, probably will find it eventually, but so far this is the only hiccup I've had with the new lein-droid.

**Comment by alexander-yakushev** [comment]
There were also some major changes in how dynamic compilation is initialized. You have to use `neko.App` class as your application now. As examples see https://github.com/clojure-android/lein-droid/blob/master/sample/AndroidManifest.template.xml and https://github.com/clojure-android/lein-droid/blob/master/sample/src/java/test/leindroid/sample/SplashActivity.java

**Comment by kenrestivo** [comment]
Thanks, I discovered the template.xml thing already, and noticed some differences in the Splash. I can get the app to compile and run, I just can't connect to it from nrepl. I'll spend more time on it later.

**Comment by kenrestivo** [comment]
I am now connected via the repl.  Still many things to fix to make it compatible with new neko, but I've got it to compile and run and can connect to it. It's here if you're interested: https://github.com/kenrestivo/spazradioapp/tree/new-neko

**Comment by alexander-yakushev** [comment]
Good to know!
