### ISSUE TITLE
Using Google Play Services

### ISSUE THREAD

**Issue by BartAdv** [clojure-android/lein-droid#87]
Documentation mentions `:use-google-api` [1], as the way to use additional APIs such as the Google Play Services. However, it just looks in `sdk/add-ons` directory, whereas Google Play Services are installed in `sdk/extras'.

It's possible to refer them via `:external-classes-paths`, but shouldn't there some more easily-configurable way? Should it be hardcoded in the same way the add-ons are searched? (Not sure about this, as (don't know really why), SDK documentation mentions that one should reference local copy instead of the libs installed under sdk directory [2])

[1]: https://github.com/clojure-android/lein-droid/wiki/project.clj-options#wiki-use-google-api

[2]: http://developer.android.com/google/play-services/setup.html

**Comment by alexander-yakushev** [comment]
After a long time this issue has been open, I'm finally glad to close it. I don't expect @BartAdv to use Clojure-Android anymore, but still mentioning you. It is very easy to [include Google Play Services](https://github.com/clojure-android/lein-droid/wiki/Tutorial#google-play-services) now.

@sakuraiyuta Thank you for the work you've done on this. Sorry I've never published your guide separately. Still I very much value your contribution, and it helped me to setup the solution we have now.
