### ISSUE TITLE
Leaderboard dependencies

### ISSUE THREAD

**Issue by arundilipan** [clojure-android/lein-droid#94]
Hi guys, I'm trying to integrate either Swarm leaderboards or the Google Play Game Services leaderboards and the problem that I have is that whenever I try to use these projects as dependencies, it doesn't necessarily work. For example, if I try to <code>lein droid init</code> in the google play services directory, sure, it works. But when I include the dir as a a <code>:project-dependency</code> then all hell breaks loose. Now I'm here waiting forever for this code to compile, keeping in mind I upped the dex heap size to 4096M and I added four threads to the operation. Whenever I replace google play with swarm, Swarm is imported alright, but the manifests aren't merged, and I'm getting an error. Does anyone have any advice? Zach Oakes told me to bring the issue up here.

**Comment by alexander-yakushev** [comment]
@arundilipan Sorry this being fixed only now. Since version `0.4.0-alpha5` lein-droid properly supports AAR packages with manifest merging, resources and everything. [Guide](https://github.com/clojure-android/lein-droid/wiki/Tutorial#libraries-and-dependencies).
